[2022-08-13 11:33:33,917] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.create_raw_data_dir manual__2022-08-13T11:33:32.469419+00:00 [queued]>
[2022-08-13 11:33:33,927] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.create_raw_data_dir manual__2022-08-13T11:33:32.469419+00:00 [queued]>
[2022-08-13 11:33:33,928] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-13 11:33:33,930] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-13 11:33:33,931] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-13 11:33:33,946] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_raw_data_dir> on 2022-08-13 11:33:32.469419+00:00
[2022-08-13 11:33:33,953] {standard_task_runner.py:52} INFO - Started process 910 to run task
[2022-08-13 11:33:33,956] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'create_raw_data_dir', 'manual__2022-08-13T11:33:32.469419+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp9yd2rmyh', '--error-file', '/tmp/tmpshoe8qph']
[2022-08-13 11:33:33,957] {standard_task_runner.py:80} INFO - Job 309: Subtask create_raw_data_dir
[2022-08-13 11:33:34,028] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.create_raw_data_dir manual__2022-08-13T11:33:32.469419+00:00 [running]> on host 4bbb34367c41
[2022-08-13 11:33:34,121] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=create_raw_data_dir
AIRFLOW_CTX_EXECUTION_DATE=2022-08-13T11:33:32.469419+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-13T11:33:32.469419+00:00
[2022-08-13 11:33:34,123] {ETL_Raizen.py:27} INFO - Dir already exists
[2022-08-13 11:33:34,124] {python.py:173} INFO - Done. Returned value was: None
[2022-08-13 11:33:34,141] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=create_raw_data_dir, execution_date=20220813T113332, start_date=20220813T113333, end_date=20220813T113334
[2022-08-13 11:33:34,169] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-13 11:33:34,224] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
