[2022-08-12 11:41:08,203] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:41:00.989849+00:00 [queued]>
[2022-08-12 11:41:08,214] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:41:00.989849+00:00 [queued]>
[2022-08-12 11:41:08,215] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:41:08,216] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 11:41:08,216] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:41:08,232] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_into_xlsx> on 2022-08-12 11:41:00.989849+00:00
[2022-08-12 11:41:08,237] {standard_task_runner.py:52} INFO - Started process 660 to run task
[2022-08-12 11:41:08,241] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'convert_xls_into_xlsx', 'manual__2022-08-12T11:41:00.989849+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpc7in4_bp', '--error-file', '/tmp/tmpqv1pt88k']
[2022-08-12 11:41:08,244] {standard_task_runner.py:80} INFO - Job 172: Subtask convert_xls_into_xlsx
[2022-08-12 11:41:08,322] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:41:00.989849+00:00 [running]> on host 3c4d8e0d9450
[2022-08-12 11:41:08,410] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_into_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T11:41:00.989849+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T11:41:00.989849+00:00
[2022-08-12 11:41:08,412] {ETL_Raizen.py:47} INFO - Converting file .xls into .xlsx using libreoffice
[2022-08-12 11:41:11,054] {ETL_Raizen.py:49} INFO - File .xls succesfully converted into .xlsx
[2022-08-12 11:41:11,056] {python.py:173} INFO - Done. Returned value was: None
[2022-08-12 11:41:11,088] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=convert_xls_into_xlsx, execution_date=20220812T114100, start_date=20220812T114108, end_date=20220812T114111
[2022-08-12 11:41:11,148] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 11:41:11,232] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
