[2022-08-11 23:35:02,839] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-11T23:34:54.412100+00:00 [queued]>
[2022-08-11 23:35:02,916] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-11T23:34:54.412100+00:00 [queued]>
[2022-08-11 23:35:02,918] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 23:35:02,919] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-11 23:35:02,920] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 23:35:03,004] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): creating_raw_data_dir> on 2022-08-11 23:34:54.412100+00:00
[2022-08-11 23:35:03,027] {standard_task_runner.py:52} INFO - Started process 6370 to run task
[2022-08-11 23:35:03,059] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'creating_raw_data_dir', 'manual__2022-08-11T23:34:54.412100+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp6ljlkl27', '--error-file', '/tmp/tmpi7ljbz8y']
[2022-08-11 23:35:03,063] {standard_task_runner.py:80} INFO - Job 87: Subtask creating_raw_data_dir
[2022-08-11 23:35:03,568] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-11T23:34:54.412100+00:00 [running]> on host 53e7d4a502e6
[2022-08-11 23:35:04,033] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=creating_raw_data_dir
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T23:34:54.412100+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T23:34:54.412100+00:00
[2022-08-11 23:35:04,046] {ETL_Raizen.py:28} INFO - Dir already exists
[2022-08-11 23:35:04,052] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 23:35:04,128] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=creating_raw_data_dir, execution_date=20220811T233454, start_date=20220811T233502, end_date=20220811T233504
[2022-08-11 23:35:04,231] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 23:35:04,462] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
