[2022-08-11 21:13:53,584] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.teste_hello_world2 scheduled__2022-08-11T12:30:00+00:00 [queued]>
[2022-08-11 21:13:53,651] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.teste_hello_world2 scheduled__2022-08-11T12:30:00+00:00 [queued]>
[2022-08-11 21:13:53,655] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 21:13:53,659] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-11 21:13:53,660] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 21:13:54,237] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): teste_hello_world2> on 2022-08-11 12:30:00+00:00
[2022-08-11 21:13:54,250] {standard_task_runner.py:52} INFO - Started process 79 to run task
[2022-08-11 21:13:54,265] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'teste_hello_world2', 'scheduled__2022-08-11T12:30:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmptzznqgyx', '--error-file', '/tmp/tmpo7dj0740']
[2022-08-11 21:13:54,266] {standard_task_runner.py:80} INFO - Job 14: Subtask teste_hello_world2
[2022-08-11 21:13:54,705] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.teste_hello_world2 scheduled__2022-08-11T12:30:00+00:00 [running]> on host 53e7d4a502e6
[2022-08-11 21:13:55,015] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=teste_hello_world2
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T12:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-11T12:30:00+00:00
[2022-08-11 21:13:55,030] {logging_mixin.py:115} INFO - Hello Workd 2
[2022-08-11 21:13:55,034] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 21:13:55,101] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=teste_hello_world2, execution_date=20220811T123000, start_date=20220811T211353, end_date=20220811T211355
[2022-08-11 21:13:55,179] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 21:13:55,296] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
