[2022-08-11 21:54:08,880] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-11T21:53:56.643778+00:00 [queued]>
[2022-08-11 21:54:08,945] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-11T21:53:56.643778+00:00 [queued]>
[2022-08-11 21:54:08,950] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 21:54:08,951] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-11 21:54:08,964] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 21:54:09,062] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): creating_raw_data_dir> on 2022-08-11 21:53:56.643778+00:00
[2022-08-11 21:54:09,080] {standard_task_runner.py:52} INFO - Started process 1550 to run task
[2022-08-11 21:54:09,095] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'creating_raw_data_dir', 'manual__2022-08-11T21:53:56.643778+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp7fn_f0wo', '--error-file', '/tmp/tmpo407m9cm']
[2022-08-11 21:54:09,098] {standard_task_runner.py:80} INFO - Job 23: Subtask creating_raw_data_dir
[2022-08-11 21:54:09,306] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-11T21:53:56.643778+00:00 [running]> on host 53e7d4a502e6
[2022-08-11 21:54:09,599] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=creating_raw_data_dir
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T21:53:56.643778+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T21:53:56.643778+00:00
[2022-08-11 21:54:09,606] {ETL_Raizen.py:31} INFO - Creating raw_data dir.
[2022-08-11 21:54:09,629] {ETL_Raizen.py:33} INFO - Dir succesfully created.
[2022-08-11 21:54:09,630] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 21:54:13,652] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=creating_raw_data_dir, execution_date=20220811T215356, start_date=20220811T215408, end_date=20220811T215413
[2022-08-11 21:54:13,748] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 21:54:14,034] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
