[2022-08-12 11:15:37,613] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-12T11:15:36.213607+00:00 [queued]>
[2022-08-12 11:15:37,627] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-12T11:15:36.213607+00:00 [queued]>
[2022-08-12 11:15:37,628] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:15:37,628] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 11:15:37,629] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:15:37,650] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): creating_raw_data_dir> on 2022-08-12 11:15:36.213607+00:00
[2022-08-12 11:15:37,656] {standard_task_runner.py:52} INFO - Started process 957 to run task
[2022-08-12 11:15:37,663] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'creating_raw_data_dir', 'manual__2022-08-12T11:15:36.213607+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpow5zceds', '--error-file', '/tmp/tmp5a_daj5f']
[2022-08-12 11:15:37,664] {standard_task_runner.py:80} INFO - Job 138: Subtask creating_raw_data_dir
[2022-08-12 11:15:37,759] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-12T11:15:36.213607+00:00 [running]> on host a471224fadbb
[2022-08-12 11:15:37,862] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=creating_raw_data_dir
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T11:15:36.213607+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T11:15:36.213607+00:00
[2022-08-12 11:15:37,864] {ETL_Raizen.py:27} INFO - Dir already exists
[2022-08-12 11:15:37,865] {python.py:173} INFO - Done. Returned value was: None
[2022-08-12 11:15:37,883] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=creating_raw_data_dir, execution_date=20220812T111536, start_date=20220812T111537, end_date=20220812T111537
[2022-08-12 11:15:37,915] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 11:15:37,966] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
