[2022-08-11 22:49:25,985] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:49:01.579235+00:00 [queued]>
[2022-08-11 22:49:26,025] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:49:01.579235+00:00 [queued]>
[2022-08-11 22:49:26,026] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:49:26,027] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-11 22:49:26,028] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:49:26,097] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_into_xlsx> on 2022-08-11 22:49:01.579235+00:00
[2022-08-11 22:49:26,112] {standard_task_runner.py:52} INFO - Started process 4313 to run task
[2022-08-11 22:49:26,136] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'convert_xls_into_xlsx', 'manual__2022-08-11T22:49:01.579235+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp_wbe89si', '--error-file', '/tmp/tmpyd07yzrn']
[2022-08-11 22:49:26,139] {standard_task_runner.py:80} INFO - Job 67: Subtask convert_xls_into_xlsx
[2022-08-11 22:49:26,566] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:49:01.579235+00:00 [running]> on host 53e7d4a502e6
[2022-08-11 22:49:27,239] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_into_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T22:49:01.579235+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T22:49:01.579235+00:00
[2022-08-11 22:49:27,247] {ETL_Raizen.py:48} INFO - Converting file .xls into .xlsx using libreoffice
[2022-08-11 22:49:55,958] {ETL_Raizen.py:50} INFO - File .xls succesfully converted into .xlsx
[2022-08-11 22:49:55,994] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 22:49:56,163] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=convert_xls_into_xlsx, execution_date=20220811T224901, start_date=20220811T224925, end_date=20220811T224956
[2022-08-11 22:49:56,354] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 22:49:56,602] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
