[2022-08-11 23:07:02,126] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T23:06:44.886293+00:00 [queued]>
[2022-08-11 23:07:02,166] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T23:06:44.886293+00:00 [queued]>
[2022-08-11 23:07:02,167] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 23:07:02,168] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-11 23:07:02,169] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 23:07:02,214] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_into_xlsx> on 2022-08-11 23:06:44.886293+00:00
[2022-08-11 23:07:02,236] {standard_task_runner.py:52} INFO - Started process 5145 to run task
[2022-08-11 23:07:02,254] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'convert_xls_into_xlsx', 'manual__2022-08-11T23:06:44.886293+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpel3ra2rn', '--error-file', '/tmp/tmpiysy8myg']
[2022-08-11 23:07:02,263] {standard_task_runner.py:80} INFO - Job 77: Subtask convert_xls_into_xlsx
[2022-08-11 23:07:02,448] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T23:06:44.886293+00:00 [running]> on host 53e7d4a502e6
[2022-08-11 23:07:02,619] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_into_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T23:06:44.886293+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T23:06:44.886293+00:00
[2022-08-11 23:07:02,623] {ETL_Raizen.py:48} INFO - Converting file .xls into .xlsx using libreoffice
[2022-08-11 23:07:17,027] {ETL_Raizen.py:50} INFO - File .xls succesfully converted into .xlsx
[2022-08-11 23:07:17,028] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 23:07:17,070] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=convert_xls_into_xlsx, execution_date=20220811T230644, start_date=20220811T230702, end_date=20220811T230717
[2022-08-11 23:07:17,151] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 23:07:17,297] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
